### ISSUE TITLE
Request Full Dataset.

### ISSUE THREAD

**Issue by thucz** [DL3DV-10K/Dataset#1]
Hi! When do you plan to release all the datasets including poses and nerf depths?

**Comment by ShengCN** [comment]
Hi @thucz , thanks for your interest. We will release the benchmark dataset (poses + results) very soon. 

The full dataset needs additional manual efforts to filter out sensitive regions. We will gradually release the full dataset, e.g. 1K data first, then 2K, 3K, etc.  But overall we will work hard to release the whole dataset in 1~2 months.

**Comment by Parskatt** [comment]
Hi @ShengCN ! Great dataset. Am I understanding correctly that only the benchmark dataset (140 videos) have nerf depth?

I'm also wondering whether you could provide the sparse colmap results, in particular the cameras/images/pointcloud .bin . This would make it easier to compute, e.g., overlaps between images. I think this should not take too much space compared to the videos themselves. Sorry if this is already uploaded somewhere, I couldn't find it except for in the samples.

**Comment by ShengCN** [comment]
Hi @Parskatt, sure, we will provide it! Not everyone needs to use it, but I guess a subset of users need to work on it. So we created a repo [here](https://huggingface.co/datasets/DL3DV/DL3DV-ALL-ColmapCache/tree/main). We will upload it in one or two days. Will notify you when it is ready.

**Comment by LuLing06** [comment]
@Parskatt, we uploaded the colmap cache files here: https://huggingface.co/datasets/DL3DV/DL3DV-ALL-ColmapCache.

**Comment by justachetan** [comment]
Hi, Thank you for uploading the colmap cache files. However, when I try to download them, I am getting errors

```
(…)bc45b3ce27c7e2428470bc8732bf1e84f0b5.zip: 100%|██████████████████████████████████████████████████████████| 190M/190M [00:04<00:00, 45.4MB/s]
NoneType: None7e2428470bc8732bf1e84f0b5.zip:  99%|█████████████████████████████████████████████████████████▋| 189M/190M [00:04<00:00, 54.3MB/s]
Retry 1
(…)2e26a9e02aae793cf20ee9d8835dd6084590.zip: 100%|██████████████████████████████████████████████████████████| 291M/291M [00:07<00:00, 41.2MB/s]
NoneType: Nonee793cf20ee9d8835dd6084590.zip: 100%|██████████████████████████████████████████████████████████| 291M/291M [00:07<00:00, 37.6MB/s]
Retry 1
(…)e45a1de5f37d6076c6b8baedc9386b1fb526.zip: 100%|██████████████████████████████████████████████████████████| 240M/240M [00:05<00:00, 47.4MB/s]
NoneType: Noned6076c6b8baedc9386b1fb526.zip: 100%|██████████████████████████████████████████████████████████| 240M/240M [00:05<00:00, 65.7MB/s]
Retry 1
(…)60a7d89c5840891acb74c26b980ea3ce4604.zip: 100%|██████████████████████████████████████████████████████████| 280M/280M [00:05<00:00, 49.6MB/s]
```

This is for the 4K subset at 960P resolution. Kindly advise how to proceed.

**Comment by ShengCN** [comment]
@justachetan Have you solved this issue? I did not see any errors in your logging. The "Retry 1" is not an error message.

**Comment by justachetan** [comment]
Hi @ShengCN Thanks for your response. I tried downloading the 4K subset, but the script only downloaded 1K files. Here is the command that I used.

```
python3 download.py --odir /phoenix/S9/DL3DV-10K/ --subset 4K --resolution 960P --file_type colmap_cache
```

**Comment by justachetan** [comment]
Hi @ShengCN any updates on this? Would be thankful for some guidance on how to download image+poses and colmap_caches for the full dataset!

**Comment by Parskatt** [comment]
Isnt 1K files expected? 4K means id 3000-3999, not 4000 images :D

**Comment by justachetan** [comment]
Ohhh, I am so sorry! now it makes sense. I will try the other subsets. Thanks!
