### ISSUE TITLE
How to download images from 5K to 7K

### ISSUE THREAD

**Issue by ewrfcas** [DL3DV-10K/Dataset#10]
![image](https://github.com/DL3DV-10K/Dataset/assets/12042259/1a3d02aa-1d6e-4a63-8c93-e24cbdcea3c0)
Though the news said that 7k dataset is ready for download, we could only download 1k~4k images.

**Comment by ShengCN** [comment]
The download.py script has been updated. Try again. Feel free to report any problems you have.

**Comment by shenyehui** [comment]
> The download.py script has been updated. Try again. Feel free to report any problems you have.

what is meaning of the subset of the benchmark to download(1k~9k images), the number of images?

**Comment by ewrfcas** [comment]
> The download.py script has been updated. Try again. Feel free to report any problems you have.

Thanks!

**Comment by ShengCN** [comment]
> > The download.py script has been updated. Try again. Feel free to report any problems you have.
> 
> what is meaning of the subset of the benchmark to download(1k~9k images), the number of images?

@shenyehui We split the 10K dataset into 10 subsets. For example, 1K means the 0~1K subset, 2K means the 1K~2K subset part.
