### ISSUE TITLE
How to generate depth image

### ISSUE THREAD

**Issue by Nightmare-n** [DL3DV-10K/Dataset#12]
Thanks for your excellent work! I would like to ask how can I generate a depth image for each rgb image from the provided colmap files?

**Comment by ShengCN** [comment]
Colmap should only have sparse depth information. 3D GS code could initialize GS based on the depth information. So maybe you could find useful information by reading 3D GS source code.

**Comment by ShengCN** [comment]
To obtain dense depth, one way is to train a NeRF/3DGS and get the depth from NeRF/3DGS.
