### ISSUE TITLE
How this dataset was made？

### ISSUE THREAD

**Issue by shenyehui** [DL3DV-10K/Dataset#16]
Thank you very much for your dataset, but I still need to make a similar dataset myself for my work, may I ask how your dataset was made and especially how the transforms.json file was obtained?

**Comment by shenyehui** [comment]
> Feel free to check our '[data preparation](https://github.com/DL3DV-10K/Dataset?tab=readme-ov-file#data-preparation)' section in the main page.

Hello, I understand how you collect the data, but what tool is used to generate the transforms.json file?

**Comment by LuLing06** [comment]
You can use COLMAP to estimate the camera parameters. The transforms.json is the same format as [Nerfstudio](https://docs.nerf.studio/). Refer to the [issue4 for details](https://github.com/DL3DV-10K/Dataset/issues/4).

**Comment by shenyehui** [comment]
> You can use COLMAP to estimate the camera parameters. The transforms.json is the same format as [Nerfstudio](https://docs.nerf.studio/). Refer to the [issue4 for details](https://github.com/DL3DV-10K/Dataset/issues/4).

Thank you!

**Comment by shenyehui** [comment]
> You can use COLMAP to estimate the camera parameters. The transforms.json is the same format as [Nerfstudio](https://docs.nerf.studio/). Refer to the [issue4 for details](https://github.com/DL3DV-10K/Dataset/issues/4).

I used nerfstudio to get all the poses of the images successfully, but the order of saving to transforms.json is quite confusing (not from frame_00001 to frame_00300), while the order of DL3DV's transforms.json is from frame_00001 to frame The order of DL3DV's transforms.json is from frame_00001 to frame_00300, is this something you guys adjusted the messy order to normal order by yourselves?（The command I use is (ns-process-data video --data data/nerfstudio/room.mp4 --output-dir outputs/room)）
