### ISSUE TITLE
How to calculate the distance between two matrices in transform.json in the world coordinate system?

### ISSUE THREAD

**Issue by shenyehui** [DL3DV-10K/Dataset#17]
Thanks for your dataset, but for my work (localization) I need to know the distance between two camera frames in the world coordinate system, how can I calculate the distance in the real world from the data in transform.json?

**Comment by ShengCN** [comment]
The transform.json has the camera matrix. You can decompose the matrix into R and T. Then measure the distance based on your distance metric.
