### ISSUE TITLE
Can only 1K-7K be downloaded for 960P?

### ISSUE THREAD

**Issue by thucz** [DL3DV-10K/Dataset#19]
Traceback (most recent call last):
  File "/group/40046/public_datasets/3d_datasets/DL3DV-10K/download.py", line 229, in <module>
    assert params.subset in ['1K', '2K', '3K', '4K', '5K', '6K', '7K'], 'Only support subset 1K-7K so far'
AssertionError: Only support subset 1K-7K so far

**Comment by ShengCN** [comment]
Hi @

**Comment by ShengCN** [comment]
We put efforts on filtering sensitive data to satisfy many rules. Now the 10K dataset is out! You can download all the dataset now.
