### ISSUE TITLE
camera infos for the 1k video not found

### ISSUE THREAD

**Issue by Wolfwjs** [DL3DV-10K/Dataset#2]
Great job! The corresponding camera infos for the [1K video](https://huggingface.co/datasets/DL3DV/DL3DV-ALL/tree/main/1K) were not found.

**Comment by ShengCN** [comment]
Hi, thank you for your interest. We just uploaded the 1K poses for the 1K video. 

We also provide a 1080P version frames with poses here: https://huggingface.co/datasets/DL3DV/DL3DV-ALL-1080P. This repo has more uploaded data and should consumes less space for ease of use.
