### ISSUE TITLE
How can I transform the poses (nerfstudio format) to opencv convention from OpenGL convention?

### ISSUE THREAD

**Issue by thucz** [DL3DV-10K/Dataset#21]
I try to flip the y and z axes direction of the camera-to-world matrix but it seems that it is not enough. when I train generalizable Gaussian Splatting on DL3DV. The RGB loss suddenly increased a lot and failed.
```
c2w[..., :, 1:3] *= -1
```

**Comment by ShengCN** [comment]
It seems to be code dependent. Have you figured out what happened in your code?
