### ISSUE TITLE
Missing images.bin file for camera extrinsics in gaussian splatting

### ISSUE THREAD

**Issue by klnavaneet** [DL3DV-10K/Dataset#22]
Hi. Thanks for releasing the dataset, it is great! I am trying to use it for 3D Gaussian splatting (3DGS). 3DGS code assumes there is a file named images.bin in the <scene_name>/sparse/0 directory with the camera extrinsics information. This file seems to be missing in the provided dataset. Is this information part of any other files or is it possible to add this file?

**Comment by LuLing06** [comment]
The [DL3DV-140](https://huggingface.co/datasets/DL3DV/DL3DV-Benchmark) provides 140 scenes with both nerfstudio and gaussian splatting (GS) formats for benchmarking Novel View Synthesis. If you want to process more GS format, you may need to post-process the data. [Here is the source](https://www.youtube.com/watch?v=wuKhEGCt6ks&ab_channel=TheNeRFGuru) to transfer to GS format.  GS also released the code to [convert the format](https://github.com/graphdeco-inria/gaussian-splatting/tree/472689c0dc70417448fb451bf529ae532d32c095). We provide the [Colmapcache](https://huggingface.co/datasets/DL3DV/DL3DV-ALL-ColmapCache) folder, which may be useful for post-process.

**Comment by LuLing06** [comment]
To address the image.bin issue. Please refer to the [example](https://huggingface.co/datasets/DL3DV/DL3DV-Benchmark/tree/main/032dee9fb0a8bc1b90871dc5fe950080d0bcd3caf166447f44e60ca50ac04ec7/gaussian_splat/sparse/0) such as: 
-DL3DV
--DL3DV-Benchmark
---scene-hashID(e,g, 032dee9fb0a8bc1b90871dc5fe950080d0bcd3caf166447f44e60ca50ac04ec7)
----gaussian-splatting
-----spares
------0
where you will see
![image](https://github.com/user-attachments/assets/147c78eb-641a-40ce-927e-7dc3681e2865)

Or, you can simply modify the [download script in 82 line ](https://huggingface.co/datasets/DL3DV/DL3DV-Benchmark/blob/f46d0729bc19b0affc58ee1279f22e79c3c86873/download.py#L82)
