### ISSUE TITLE
how are training images sampled for benchmark

### ISSUE THREAD

**Issue by arthurhero** [DL3DV-10K/Dataset#23]
Hi,

Thank you for providing this fantastic new dataset!

In the paper, the authors mentioned "We use 7/8 of the images for training and 1/8 of the images for testing" while evaluating the sota methods on the dl3dv benchmark. How are the 7/8 image sampled? Are they sampled randomly? Or uniformly?

Thank you,
Ziwen

**Comment by LuLing06** [comment]
Hi Ziwen,

We uniformly sampled the data for training. The same approach as used in [Mip-NeRF 360](https://jonbarron.info/mipnerf360/).

**Comment by arthurhero** [comment]
Got it! Thank you very much!
