### ISSUE TITLE
Some suggestions to the data collection

### ISSUE THREAD

**Issue by yifanjiang19** [DL3DV-10K/Dataset#24]
Dear authors,

Thanks for open sourcing this dataset. DL3DV looks great and thank you for your contributions to the community.

Beside, there are some kind suggestions to the collection pipeline that might help you avoid low-quality data. I notice that there is some white balancing error and blurry artifacts, e.g, color suddenly change during 00:18 - 00:20 in this [example](https://huggingface.co/datasets/DL3DV/DL3DV-10K-Sample/tree/main/5c3af581028068a3c402c7cbe16ecf9471ddf2897c34ab634b7b1b6cf81aba00), and blurry frame in `1K/fff0ff507a7d886e7c843949050a7b3f7f8644d956f2029316b749c6625d1b1b`. 

You might find it helpful to 1) disable the auto white balancing (AWB) during capturing and instead use a fixed setting of white balancing; 2)set a faster exposure time (I think exposure time shorter than 1/400 should be enough, that helps you capture sharp details in the scene). 

I know 2) might bring some noise in the low-light scene and I think it is ok after some denoising algorithm, in the context of 3D data preparation. 

Hope you find it helpful during your (potential) next dataset collection plan. And again, thanks for the great contribution to the community!

Best,

**Comment by LuLing06** [comment]
Thanks for suggestions. We will consider it into our future data collection process.
