### ISSUE TITLE
ETA  for 8K~10K ?

### ISSUE THREAD

**Issue by emjay73** [DL3DV-10K/Dataset#26]
Thank you for sharing this amazing dataset!

I wonder when it will be the estimated day of arrival for the rest of the dataset.

The dataset's name implies that it should be 10K, but when I tried to download the 960P dataset, it only had 1K to 7K.

Thank you!

**Comment by LuLing06** [comment]
We apologize for the delay due to the data sensitivity check.  The rest of data will be released within this week.

**Comment by ewrfcas** [comment]
The same question. Any updates?

**Comment by LuLing06** [comment]
They are uploaded. Feel free to download all videos/images

**Comment by ShengCN** [comment]
Remember to update the `download.py` script. Then just run the script to download the remaining data.
