### ISSUE TITLE
Nerf-estimated depth maps

### ISSUE THREAD

**Issue by mdfirman** [DL3DV-10K/Dataset#27]
Hello and thank you for releasing this great dataset!

Your [website](https://dl3dv-10k.github.io/DL3DV-10K/) states that "Each video has calibrated camera poses, NeRF estimated depth, point clouds and 3D meshes."

![image](https://github.com/user-attachments/assets/3d657536-f136-4506-9636-466843e8575a)

I had a look through the [sample data on huggingface](https://huggingface.co/datasets/DL3DV/DL3DV-10K-Sample/tree/main) but I couldn't see any nerf estimated depth maps there. Are they available separately?

Many thanks

**Comment by LuLing06** [comment]
Hi, thanks for pointing it out. The depth estimation is under processing now. It will take a longer time to be ready. However, you are more than welcome and free to download the dataset and process the depth.

**Comment by rwn17** [comment]
Any update on depth 👀? Many thanks!

**Comment by Liu-SD** [comment]
Any update on depth 👀?

**Comment by ShengCN** [comment]
@Liu-SD @rwn17 Thanks for tracking this. There would be a release of 3D-GS with depth for each scene by [Yihang](https://yhangchen.github.io/). The repo link: https://huggingface.co/datasets/DL3DV/DL3DV-1-7K-960P-image-depth. Still uploading, will approve all the users when the uploading finished.

**Comment by PLUS-WAVE** [comment]
Great work! Is there any update on depth? We still can't access the [https://huggingface.co/datasets/DL3DV/DL3DV-1-7K-960P-image-depth.](https://huggingface.co/datasets/DL3DV/DL3DV-1-7K-960P-image-depth) 🥺
