### ISSUE TITLE
Access to dataset DL3DV/DL3DV-ALL-960P is restricted

### ISSUE THREAD

**Issue by ewrfcas** [DL3DV-10K/Dataset#28]
I have been granted access to https://huggingface.co/datasets/DL3DV/DL3DV-ALL-960P. 
![image](https://github.com/user-attachments/assets/fd50d165-b10e-49b6-932b-9a1945462ff2)
And I have logged my account through ```huggingface-cli login``` with my newly generated tokens. But the download command ```python download.py --odir DL3DV-10K --subset 8K --resolution 960P --file_type images+poses --clean_cache``` is still failed with:

Cannot access gated repo for url https://huggingface.co/datasets/DL3DV/DL3DV-ALL-960P/resolve/main/8K/d7bc6edfea46c719d093a05f70e25988d7ecf55517001560a006ec76e04c1119.zip.
Access to dataset DL3DV/DL3DV-ALL-960P is restricted. You must be authenticated to access it.

**Comment by emjay73** [comment]
Same issue here.
When I try to download the newly uploaded 8K, I get the following message:
![image](https://github.com/user-attachments/assets/e00884a9-f9eb-4533-98dd-fc059e0378c5)
However, I have been granted access to the dataset already.
![image](https://github.com/user-attachments/assets/9c18dde7-98ea-4417-a525-cc7e11c8908c)

**Comment by ewrfcas** [comment]
This issue is address by adding
```
from huggingface_hub import login

login(token="xxxx")
```
to the download.py.

But I further found that only 1K~8K can be downloaded through the script, 9K~11K can be only seen in the huggingface page, which could not be download through the script.

Downloading: 0it [00:00, ?it/s]
Summary: 0/0 files downloaded successfully
Download Done.

**Comment by emjay73** [comment]
@ewrfcas By doing so, I was able to solve the authentication issue. Thanks! And yes, I also was not able to download 9K~11K using the following command.
```
python download.py --odir DL3DV-ALL-960P --subset 9K --resolution 960P --file_type images+poses
```
Showing,,
```
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/.cache/huggingface/token
Login successful
Downloading: 0it [00:00, ?it/s]
Summary: 0/0 files downloaded successfully
Download Done. Refer to DL3DV-ALL-960P
```

**Comment by Fusroda-h** [comment]
Hey, I'm running into an access issue when trying to download colmap_cache.

I was able to download images+poses just fine, so my token seems to be working. Also, I’ve been granted access to all DL3DV datasets (I see the "You have been granted access to this dataset" message for all of them). My Hugging Face token has all repository permissions enabled, so I have no idea what's causing this.

Here’s what happens:
```bash
$ python download.py --odir DL3DV-10K --subset 1K --resolution 960P --file_type images+poses

Token is valid (permission: fineGrained).
Login successful
Downloading: 100%|████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 1423.10it/s]
Summary: 1000/1000 files downloaded successfully
Download Done. Refer to DL3DV-10K
```

But when I try to download colmap_cache, I get this:
```bash
$ python download.py --odir DL3DV-10K --subset 1K --resolution 960P --file_type colmap_cache

Token is valid (permission: fineGrained).
Login successful
You have not granted the access yet. Go to the relevant Hugging Face repo (https://huggingface.co/datasets/DL3DV/DL3DV-ALL-ColmapCache) and apply for access.
```

+ I also tried adding "login" to download.py like [here](https://github.com/DL3DV-10K/Dataset/issues/28#issuecomment-2336523123), but did't work.

> This issue is address by adding
> 
> ```
> from huggingface_hub import login
> 
> login(token="xxxx")
> ```
> 
> to the download.py.
> 
> But I further found that only 1K to 8K can be downloaded through the script, 9K to 11K can be only seen in the huggingface page, which could not be download through the script.
> 
> These data subset seem like empty: Downloading: 0it [00:00, ?it/s] Summary: 0/0 files downloaded successfully Download Done.
> 
> Moreover, I find that 8K only contains 120 scenes.


I already have access, so I’m not sure why it's saying I don’t.
Am I missing something here? Any help would be appreciated!

Thanks in advance!
