### ISSUE TITLE
Unable to download subset data using download.py file. (8K-11K)

### ISSUE THREAD

**Issue by emjay73** [DL3DV-10K/Dataset#29]
As mentioned in the previous issue( https://github.com/DL3DV-10K/Dataset/issues/28#issuecomment-2336523123 ), 
the 9K to 11K subsets could not be downloaded through the script, even though they are visible on the Hugging Face page.

Download script:
```
python download.py --odir DL3DV-ALL-960P --subset 9K --resolution 960P --file_type images+poses
```
output
```
Downloading: 0it [00:00, ?it/s]
Summary: 0/0 files downloaded successfully
Download Done.
```
Additionally, the 8K subset downloaded using the script only contains partial data.

**Comment by OasisYang** [comment]
I guess the meta file [DL3DV-valid.csv](https://github.com/DL3DV-10K/Dataset/blob/main/cache/DL3DV-valid.csv) should be updated to download the data after 7K.

**Comment by ShengCN** [comment]
@OasisYang @emjay73 All the 10K data have been uploaded. Update the `[download.py](https://github.com/DL3DV-10K/Dataset/blob/main/scripts/download.py)` script and just run the script to download the remaining data.

Feel free to post any problems you have!
