### ISSUE TITLE
License/clarifications on usage

### ISSUE THREAD

**Issue by Parskatt** [DL3DV-10K/Dataset#3]
I'm really excited for this dataset but I'm wondering about the non-commercial license.
It would be great if the license could clarify if weights of non-generative models inherit the non-commercial license.

For example, I'm interested in training models for image matching, which does not aim to replicate the original data.
I feel that downstream commercial usage of this type of model shouldn't be problematic, but in its current state its very difficult to know if the license prohibits such usage. 

A further example could be training monodepth networks, or other scene agnostic types of models that are conditioned on images.

**Comment by LuLing06** [comment]
This is a very nice point. There is no restriction for the usage of the trained weight  for the downstream task. We will update the license soon.  The  goal is to make the datasets available to the general public.
