### ISSUE TITLE
Drone camera labeling

### ISSUE THREAD

**Issue by KIMGEONUNG** [DL3DV-10K/Dataset#35]
Hi, thank you for your helpful dataset.

Can I know about drone camera labelding? or is there a plan to label drone camera?

**Comment by ShengCN** [comment]
Hi @KIMGEONUNG, drone data has been processed in the 10K dataset. We just filter them out so that it's easier for people to find the original video.

**Comment by shawnzxf** [comment]
Hi @ShengCN , 

> We just filter them out so that it's easier for people to find the original video.

I found there are still some drone videos in the 10k dataset based on hashes from this dataset https://huggingface.co/datasets/DL3DV/DL3DV-Drone/tree/main/All-Drone-Videos

do you know what is the best way to see if a video is drone camera or not?

cc @LuLing06
