### ISSUE TITLE
A question about setup of dateset

### ISSUE THREAD

**Issue by shenyehui** [DL3DV-10K/Dataset#8]
Sorry, I found the nerf-h training method I referenced in training, which uses Cambridge dataset to train nerf, and provides a setup_world.json file to manually align the scales in addition to pose as shown in the code below, do I need to set up such a file to train with DL3DV as well? If yes, how do I set it up?

if rescale_coord.
    sc=train_set.pose_scale # manual tuned factor, align with colmap scale
    all_poses[:,:3,3] *= sc

    ### Quite ugly ### 
    ## move centre of camera pose
    if train_set.move_all_cam_vec ! = [0.,0.,0.].
        all_poses[:, :3, 3] += train_set.move_all_cam_vec

    if train_set.pose_scale2 ! = 1.0: all_poses[:, :3, 3] += train_set.
        all_poses[:, :3, 3] *= train_set.pose_scale2

**Comment by shenyehui** [comment]
> Sorry, I found the nerf-h training method I referenced in training, which uses Cambridge dataset to train nerf, and provides a setup_world.json file to manually align the scales in addition to pose as shown in the code below, do I need to set up such a file to train with DL3DV as well? If yes, how do I set it up?
> 
> if rescale_coord. sc=train_set.pose_scale # manual tuned factor, align with colmap scale all_poses[:,:3,3] *= sc
> 
> ```
> ### Quite ugly ### 
> ## move centre of camera pose
> if train_set.move_all_cam_vec ! = [0.,0.,0.].
>     all_poses[:, :3, 3] += train_set.move_all_cam_vec
> 
> if train_set.pose_scale2 ! = 1.0: all_poses[:, :3, 3] += train_set.
>     all_poses[:, :3, 3] *= train_set.pose_scale2
> ```

This may be the code used to manually adjust the centred postures, and I've had results using your postures (which are not centred) directly for training. Thanks for your dataset!

**Comment by ShengCN** [comment]
@shenyehui For beginners, nerfstudio may be a good starting point. And their code is well-organized for code review. I suggest you take a look.

Many recent methods have been implemented inside one framework. So the code is very consistent. https://github.com/nerfstudio-project/nerfstudio
